dist: xenial   # required for Python >= 3.7
sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -U pip poetry
  - poetry install -E textract
  - poetry run python main.py list
  - poetry run python main.py config --path
  - poetry run python main.py --version
script:
    poetry run pytest
