sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
install:
  - pip install -U pip
  - pip install .
  - pip install pytest-datafiles
  - python main.py list
  - python main.py --version
script:
    py.test
