sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install poetry
  - poetry install
  - poetry run python main.py list
  - organize list
script:
    poetry run py.test
