folders: &all
  - '~/Desktop/__Inbox__'
  - '~/Downloads'
  - '~/TF Cloud/Office/_EINGANG_'

rules:
  # German VDI Nachrichten
  - filters:
    - PaperVDI
    actions:
    - Move: {dest: '~/Documents/VDI Nachrichten/VDI {year}-{month:02}-{day:02}.pdf'}
    folders: *all

  # Matches filename by regular expression
  - filters:
    - Regex: {expr: '^RG(\d{12})-sig\.pdf$'}
    actions:
    - Move: {dest: '~/TF Cloud/Office/Rechnungen/MCF 1und1'}
    folders: *all

  # 1und1 invoices
  - filters:
    - Invoice1and1
    actions:
    - Move: {dest: '~/TF Cloud/Office/Rechnungen/{year}-{month:02}-{day:02} 1und1.pdf'}
    folders: *all
