site_name: organize
repo_url: https://github.com/tfeldmann/organize/
edit_uri: edit/main/docs/
site_author: "Thomas Feldmann"
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Rules: rules.md
  - Locations: locations.md
  - Filters: filters.md
  - Actions: actions.md
  - Docker: docker.md
  - Changelog: changelog.md
  - Migrating from older versions: migrating.md
plugins:
  - search
  - include-markdown
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: false
            show_root_toc_entry: false
            show_root_heading: false
            show_source: true
watch:
  - organize
  - docs

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

theme:
  name: readthedocs
