[tool.poetry]
name = "organize-tool"
version = "1.10.1"
description = "The file management automation tool"
packages = [
    { include = "organize" },
]
authors = ["Thomas Feldmann <mail@tfeldmann.de>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tfeldmann/organize"
documentation = "https://organize.readthedocs.io"
keywords = ["file", "management", "automation", "tool", "organization", "rules", "yaml"]
classifiers = [
    # Full list: https://pypi.python.org/pypi?%3Aaction=list_classifiers
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Utilities",
]

[tool.poetry.scripts]
organize = "organize.cli:main"

[tool.poetry.dependencies]
python = "^3.6.2"
fs = "^2.4.14"
rich = "^11.0.0"
docopt = "^0.6.2"
PyYAML = "^5.4.1"
Send2Trash = "^1.8.0"
ExifRead = "^2.3.2"
textract = { version = "^1.6.4", optional = true }
simplematch = "^1.3"
macos-tags = { version = "^1.5.1", markers = "sys_platform == 'darwin'"}
schema = "^0.7.5"

[tool.poetry.extras]
textract = ["textract"]

[tool.poetry.dev-dependencies]
pip = "^21.3.1"
pytest = "^4.6"
pylint = "^2.3"
ipdb = "^0.12.0"
sphinx = "^3.1.0"
sphinx-rtd-theme = "^0.5.2"
mypy = "^0.812"
flake8 = "^3.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
