name: pythonpackage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install -E textract

      - name: General info
        run: |
          poetry run python main.py list
          poetry run python main.py config --path
          poetry run python main.py --version

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 --count --select=E9,F63,F7,F82 --show-source --statistics organize
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics organize

      - name: Test with pytest
        run: |
          poetry run pytest

      - name: Check with MyPy
        run: |
          poetry run mypy -porganize
