name: tests

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Setup Environment
        run: |
          python3 -m pip install --upgrade pip poetry lxml

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false &&
          poetry install --with=dev --extras=textract

      - name: Version info
        run: |
          python main.py --version

      - name: Test with pytest
        run: |
          pytest

      - name: Check with MyPy
        run: |
          mypy organize main.py
