name: tests

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# https://github.com/python-poetry/poetry/issues/8623
env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Setup Environment
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
        run: |
          python3 -m pip install -U pip setuptools
          python3 -m pip install poetry==1.7.1 lxml
          poetry config virtualenvs.create false
          poetry install --with=dev --extras=textract

      - name: Version info
        run: |
          python main.py --version

      - name: Test with pytest
        run: |
          pytest

      - name: Check with MyPy
        run: |
          mypy .
